version: '3.8'

services:

  db:
    image: postgres:13.12-alpine
    container_name: tm_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=task-manager
      - POSTGRES_USER=tm-postgres-user
      - POSTGRES_PASSWORD=tm-postgres-password

  service:
    build: .
    container_name: tm_service_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task-manager
      - DB_USER=tm-postgres-user
      - DB_PASSWORD=tm-postgres-password